services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitsculpt_api_dev
    ports:
      - "5432:5432"
    volumes:
      - fitsculpt_api_dev_data:/var/lib/postgresql/data

volumes:
  fitsculpt_api_dev_data:
